#!/bin/sh
#
# /etc/rc: system boot script
#

echo "The system is coming up.  Please wait."

# Load configuration
. /etc/rc.conf

# Start device management daemon
/sbin/devfsd /dev

# Activate swap
/sbin/swapon -a

# Mount root read-only
/bin/mount -n -o remount,ro /

# Check filesystems
/sbin/fsck -A -T -C -a
if [ $? -gt 1 ]; then
    echo
    echo "***************  FILESYSTEM CHECK FAILED  ******************"
    echo "*                                                          *"
    echo "*  Please repair manually and reboot. Note that the root   *"
    echo "*  file system is currently mounted read-only. To remount  *"
    echo "*  it read-write type: mount -n -o remount,rw /            *"
    echo "*  When you exit the maintainance shell the system will    *"
    echo "*  reboot automatically.                                   *"
    echo "*                                                          *"
    echo "************************************************************"
    echo
    /sbin/sulogin -p
    echo "Automatic reboot in progress..."
    /bin/umount -a
    /bin/mount -n -o remount,ro /
    /sbin/reboot -f
    exit 0
fi

# Mount local filesystems
/bin/mount -n -o remount,rw /
/bin/rm -f /etc/mtab* 
/bin/mount -a -t nonfs

# Clean up misc files
: > /var/run/utmp
/bin/rm -rf /forcefsck /fastboot /etc/nologin \
	    /etc/shutdownpid /var/run/*.pid \
	    /var/locks/* /tmp/{.*,*} &> /dev/null

# Set kernel variables
/sbin/sysctl -p > /dev/null

# Update shared library links
/sbin/ldconfig

# Configure host name
if [ "$HOSTNAME" ]; then
    echo "hostname: $HOSTNAME"
    /bin/hostname $HOSTNAME
fi

# Start log daemons
/usr/sbin/syslogd
/usr/sbin/klogd -c 4

# Initialize random seed
if [ -f /var/run/random-seed ]; then
    /bin/cat /var/run/random-seed > /dev/urandom
fi

# Configure system clock
if [ ! -f /etc/adjtime ]; then
    echo "0.0 0 0.0" > /etc/adjtime
fi
if [ "$TIMEZONE" ]; then
    /bin/ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
fi
/sbin/hwclock --hctosys

# Load keyboard map
if [ "$KEYMAP" ]; then
    echo "keyboard: $KEYMAP"
    /bin/loadkeys -q $KEYMAP
fi

# Screen blanks after 15 minutes idle time
/usr/bin/setterm -blank 15

# Run module initialization script
if [ -x /etc/rc.modules ]; then
    /etc/rc.modules
fi

/sbin/snapptix_start.sh &

# End of file
